### ISSUE TITLE
Does openvino support dynamic conv?

### ISSUE THREAD

**Issue by yuqiu1233** [bes-dev/MobileStyleGAN.pytorch#9]
as title, thanks for your great work!

**Comment by bes-dev** [comment]
@yuqiu1233 what is "dynamic conv"?

**Comment by yuqiu1233** [comment]
@bes-dev `F.conv2d(input,weight) `
The weight is dynamic which is changed with different input.I found ncnn is not support it

**Comment by bes-dev** [comment]
@yuqiu1233 sorry. I don't understand. 
There are two types of "dynamic conv":
- weight kernel is depends on input data (computed by input).
- convolution depends on dynamic input shape (for example we want to apply convolution for input 256x256 and 512x512).

So, as I know, first case supports in openvino. Any blob is just node of graph and it doesn't matter for openvino how we get weights of convolution (constantly or by computation). What about second case, it more complicated because openvino otimizes memory layouts for network and we can't to change input size stright-forward. But if network supports shape infer, than we can make reshape for whole network handcrafted.

But I think you should refer to OpenVINO documentation or issues of the openvino repository to get more information :)

**Comment by yuqiu1233** [comment]
@bes-dev Thanks for your reply, it's helpful to me!
